apiVersion: v1
kind: Service
metadata:
  labels:
    app: debezium
  name: debezium-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: debezium-port
      port: 8080
      targetPort: 8080
  selector:
    app: debezium
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: debezium
    name: debezium
    namespace: kafka
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: debezium
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: debezium
      spec:
        containers:
          - image: asia-south1-docker.pkg.dev/fk-sandbox-fkhealth-temp-1/hello-repo/debezium-connect:latest
            imagePullPolicy: Always
            name: debezium-connect
            volumeMounts:
              - name: debezium-properties
                mountPath: "/usr/local/debezium-server-1.9/conf"
              - name: offset-storage
                mountPath: "/usr/local/debezium-server-1.9/data"
        volumes:
          - name: debezium-properties
            configMap:
              name: dbz-config
          - name: offset-storage
            persistentVolumeClaim:
              claimName: pvc-dbz