apiVersion: v1
kind: Service
metadata:
  labels:
    app: debezium
  name: debezium-service
  namespace: kafka
spec:
  type: NodePort
  ports:
    - name: debezium-port
      port: 8080
      nodePort: 32081
      targetPort: 8080
  selector:
    app: debezium
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2022-06-14T09:00:14Z"
    generation: 1
    labels:
      app: hello-app
    managedFields:
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:progressDeadlineSeconds: {}
          f:replicas: {}
          f:revisionHistoryLimit: {}
          f:selector: {}
          f:strategy:
            f:rollingUpdate:
              .: {}
              f:maxSurge: {}
              f:maxUnavailable: {}
            f:type: {}
          f:template:
            f:metadata:
              f:labels:
                .: {}
                f:app: {}
            f:spec:
              f:containers:
                k:{"name":"debezium-connect"}:
                  .: {}
                  f:image: {}
                  f:imagePullPolicy: {}
                  f:name: {}
                  f:resources: {}
                  f:terminationMessagePath: {}
                  f:terminationMessagePolicy: {}
              f:dnsPolicy: {}
              f:restartPolicy: {}
              f:schedulerName: {}
              f:securityContext: {}
              f:terminationGracePeriodSeconds: {}
      manager: kubectl-create
      operation: Update
      time: "2022-06-14T09:00:14Z"
    - apiVersion: apps/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:deployment.kubernetes.io/revision: {}
        f:status:
          f:availableReplicas: {}
          f:conditions:
            .: {}
            k:{"type":"Available"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
            k:{"type":"Progressing"}:
              .: {}
              f:lastTransitionTime: {}
              f:lastUpdateTime: {}
              f:message: {}
              f:reason: {}
              f:status: {}
              f:type: {}
          f:observedGeneration: {}
          f:readyReplicas: {}
          f:replicas: {}
          f:updatedReplicas: {}
      manager: kube-controller-manager
      operation: Update
      time: "2022-06-14T09:00:17Z"
    name: hello-app
    namespace: kafka
    resourceVersion: "28621543"
    uid: 601021a1-f83e-4317-bbb9-c0b94beb92c1
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: hello-app
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: hello-app
      spec:
        containers:
        - image: asia-south1-docker.pkg.dev/fk-sandbox-fkhealth-temp-1/hello-repo/debezium-connect:latest
          imagePullPolicy: Always
          name: debezium-connect
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: debezium-properties
              mountPath: "/usr/local/debezium-server-1.6/conf"
            - name: offset-storage
              mountPath: "/usr/local/debezium-server-1.6/data"
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
          - name: debezium-properties
            configMap:
              name: dbz-config
          - name: offset-storage
            persistentVolumeClaim:
              claimName: pvc-dbz
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-06-14T09:00:17Z"
      lastUpdateTime: "2022-06-14T09:00:17Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-06-14T09:00:14Z"
      lastUpdateTime: "2022-06-14T09:00:17Z"
      message: ReplicaSet "hello-app-5c9d484846" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1

  #apiVersion: apps/v1
  #kind: Deployment
  #metadata:
  #  name: debezium-deployment
  #  labels:
  #    app: debezium
  #spec:
  #  replicas: 1
  #  selector:
  #    matchLabels:
  #      app: debezium
  #  template:
  #    metadata:
  #      labels:
  #        app: debezium
  #    spec:
  #      containers:
  #        - name: debezium
  #          image: asia-south1-docker.pkg.dev/fk-sandbox-fkhealth-temp-1/hello-repo/debezium-connect:latest
  #          ports:
  #            - containerPort: 80
  #          volumeMounts:
  #            - name: debezium-properties
  #              mountPath: "/usr/local/debezium-server-1.6/conf"
  #      volumes:
  #        - name: debezium-properties
  #          configMap:
  #            name: dbz-config

