apiVersion: v1
kind: ConfigMap
metadata:
  name: dbz-config
  namespace: kafka
data:
  application.properties: |
    debezium.sink.type=kafka
    debezium.sink.kafka.producer.bootstrap.servers=kafka-service.kafka.svc.cluster.local:9092
    debezium.sink.kafka.producer.topic.creation.enable=true
    debezium.source.bootstrap.servers=kafka-service.kafka.svc.cluster.local:9092
    debezium.sink.kafka.producer.max.block.ms=5000
    debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
    debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    debezium.source.connector.class=io.debezium.connector.sqlserver.SqlServerConnector
    debezium.source.offset.storage=io.debezium.server.redis.RedisOffsetBackingStore
    debezium.source.offset.storage.redis.address=
    debezium.source.offset.storage.redis.user=
    debezium.source.offset.storage.redis.password=
    debezium.source.offset.storage.redis.key=
    debezium.source.offset.flush.interval.ms=0
    debezium.source.database.hostname=mssql-service
    debezium.source.database.port=1433
    debezium.source.database.user=sa
    debezium.source.database.password=
    debezium.source.database.dbname=test_db
    debezium.source.database.server.name=test_db
    debezium.sink.pravega.scope=empty
    debezium.source.table.include.list=
    database.history.kafka.bootstrap.servers=kafka-service.kafka.svc.cluster.local:9092
    debezium.source.database.history=io.debezium.relational.history.KafkaDatabaseHistory
