apiVersion: apps/v1
kind: Deployment
metadata:
  name: debezium-deployment
  labels:
    app: debezium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      containers:
        - name: debezium
          image: debezium
          ports:
            - containerPort: 80
          volumeMounts:
            - name: debezium-properties
              mountPath: "/usr/local/debezium-server-1.6/conf"
      volumes:
        - name: debezium-properties
          configMap:
            name: dbz-config

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dbz-config
  namespace: kafka
data:
  application.properties: |
    debezium.sink.type=kafka
    debezium.sink.kafka.producer.bootstrap.servers=kafka-service.kafka.svc.cluster.local:9092
    debezium.sink.kafka.producer.topic.creation.enable=true
    debezium.source.bootstrap.servers=kafka-service.kafka.svc.cluster.local:9092
    debezium.sink.kafka.producer.max.block.ms=5000
    debezium.sink.kafka.producer.key.serializer=org.apache.kafka.common.serialization.StringSerializer
    debezium.sink.kafka.producer.value.serializer=org.apache.kafka.common.serialization.StringSerializer
    debezium.source.connector.class=io.debezium.connector.sqlserver.SqlServerConnector
    debezium.source.offset.storage.file.filename=data/offsets1.dat
    debezium.source.offset.flush.interval.ms=0
    debezium.source.database.hostname=mssql-service
    debezium.source.database.port=1433
    debezium.source.database.user=sa
    debezium.source.database.password=<password>
    debezium.source.database.dbname=test_db
    debezium.source.database.server.name=test_db
    debezium.sink.pravega.scope=empty
    debezium.source.table.include.list=dbo.Persons
    debezium.source.database.history.file.filename=data/FileDatabaseHistory1.dat
    debezium.source.database.history=io.debezium.relational.history.FileDatabaseHistory

---


